# Generated by Django 5.0.4 on 2025-08-03 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_namespaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homepage',
            name='namespace',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page', to='knowledge.namespace'),
        ),
        migrations.AddField(
            model_name='namespacemember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_memebers', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='namespacemember',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_memebers', to='knowledge.namespace'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='namespaces', through='knowledge.NamespaceMember', to='businesses.employee'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='page',
            name='namespace',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='knowledge.namespace'),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddIndex(
            model_name='namespace',
            index=models.Index(fields=['slug'], name='knowledge_n_slug_4724d8_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='knowledge_p_slug_6112f2_idx'),
        ),
    ]
